In [1]:
""" Used when checked out from Git """
import sys
import os
def add_local():
    d = os.getcwd()
    assert d[-9:] == "notebooks", "This code assume that the notebook is run out of 'notebooks'. Remove this code if not needed"
    sys.path.insert( 0, d[:-10] )
    print(f"Added '{d[:-10]}' to the import path")
add_local()


Added '/mnt/c/Users/hans/OneDrive/Python3/packages/cdxcore' to the import path


In [39]:
try:
    del test
except:
    pass
try:
    del test2
except:
    pass

gc.collect()

create_sharedarray: _finalize Test 56492612
attach_sharedarray: _finalize Test 564926


1954

In [40]:
import importlib as imp
import cdxcore.npio as _
imp.reload(_)
import cdxcore.npshm as _
imp.reload(_)

import gc as gc
from cdxcore.npshm import create_shared_array
import numpy as np

test_name = "Test 56492612"

test = create_shared_array( test_name, shape=(10,3), dtype=np.int32, force=True )
print(test.shape, test.dtype, test)

create_sharedarray: Test 56492612
(10, 3) int32 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [41]:
import importlib as imp
import cdxcore.npio as _
imp.reload(_)
import cdxcore.npshm as _
imp.reload(_)

import gc as gc
from cdxcore.npshm import create_shared_array
import numpy as np

test2 = create_shared_array( test_name, shape=(4,3), dtype=np.int32, force=False )
print(test.shape, test.dtype, test)

FileExistsError: [Errno 17] File exists: '/Test 56492612'

In [44]:
import importlib as imp
import cdxcore.npio as _
imp.reload(_)
import cdxcore.npshm as _
imp.reload(_)

import gc as gc
from cdxcore.npshm import attach_shared_array
import numpy as np

test2 = attach_shared_array( test_name )
print(test.shape, test.dtype, test)

attach_sharedarray Test 56492612
attach_sharedarray: _finalize Test 56492612
(10, 3) int32 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [46]:
test[:4,0] = 1
test

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [47]:
test2

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [51]:
import importlib as imp
import cdxcore.npio as _
imp.reload(_)
import cdxcore.npshm as _
imp.reload(_)

import gc as gc
from cdxcore.npshm import read_sharedarray
import numpy as np

test2 = attach_sharedarray( test_name )
print(test.shape, test.dtype, test)
from cdxcore.npio import to_file
from cdxcore.subdir import SubDir
file_name = SubDir("!/cdxcoredummy;*.bin", create_directory=True ).full_file_name("shared")
to_file( file_name, test )

test_read = read_sharedarray( file_name, "Test_file_231312", accept_existing=True )


attach_sharedarray Test 56492612
attach_sharedarray: _finalize Test 56492612
(10, 3) int32 [[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
create_sharedarray: Test_file_231312


In [52]:
test_read2 = read_sharedarray( file_name, "Test_file_231312", accept_existing=True )

attach_sharedarray Test_file_231312


In [58]:
import importlib as imp
import cdxcore.npio as _
imp.reload(_)
import cdxcore.npshm as _
imp.reload(_)

import gc as gc
from cdxcore.npshm import linux_delete_shared_array
import numpy as np

linux_delete_shared_array( test_name, raise_on_error=True )

True

In [54]:
type(test_read2)

numpy.ndarray

In [55]:
test_read2.buf

AttributeError: 'numpy.ndarray' object has no attribute 'buf'

In [56]:
type(test_read2.data)

memoryview

In [28]:
import importlib as imp
import cdxcore.npio as _
imp.reload(_)
import cdxcore.npshm as _
imp.reload(_)

import gc as gc
from cdxcore.npshm import delete_shared_array,create_shared_array, attach_shared_array
import numpy as np

delete_shared_array( test_name, raise_on_error=True )

test_name = "Test xyz"

test1 = create_shared_array( test_name, shape=(10,3), dtype=np.int32, force=True, full=0 )
test2 = attach_shared_array( test_name, )
test1[:,1] = 1
assert np.all( test1==test2 )

delete_shared_array( test_name, raise_on_error=True )
test3 = attach_shared_array( test_name, )
test1[:,2] = 2
assert np.all( test1==test2 )
assert np.all( test1==test3 )
print("/done")

test1.base

FileExistsError: [WinError 183] File exists: 'Test xyz'

In [61]:
import platform
platform.system()

'Linux'

In [29]:
x = np.zeros((20,10))
x.base

In [30]:
print(x.base)

None
